_target_: discrete_diffusion.data.graph_generator.GraphGenerator
graph_type: "balanced_tree"
num_samples: 1000 #10000
nx_params:
  h: [2]
  r: [2]

nx_generator:
  _target_: networkx.generators.balanced_tree
