module:
  _target_: discrete_diffusion.pl_modules.classifier_pl_module.ClassifierPLModule

  model:
    _target_: discrete_diffusion.modules.classifier.classifier.Classifier
    hidden_channels: 128
    num_classes: 2

standard_model_ckpt: ${oc.env:PROJECT_ROOT}/storage/discrete_diffusion/3umps0yl/checkpoints/epoch=99-step=5599.ckpt.zip
augmented_model_ckpt: ${oc.env:PROJECT_ROOT}/storage/discrete_diffusion/3umps0yl/checkpoints/epoch=99-step=5599.ckpt.zip

data:
  _target_: discrete_diffusion.data.datamodule.GraphDataModule
  dataset_name: PROTEINS_full

  overfit: -1

  train_dirs:
    standard: ${oc.env:PROJECT_ROOT}/data/standard
    connectivity_augmented:

  max_graphs_per_dataset:
    standard:
    connectivity_augmented:

  datasets:
    train:
      _target_: discrete_diffusion.data.graph_dataset.GraphDataset
    val:
      _target_: discrete_diffusion.data.graph_dataset.GraphDataset
    test:
      _target_: discrete_diffusion.data.graph_dataset.GraphDataset


  gpus: 1

  num_workers:
    train: 8
    val: 4
    test: 4

  batch_size:
    train: 16
    val: 16
    test: 1

  val_percentage: 0.1
