data:
  _target_: discrete_diffusion.data.datamodule.GraphDataModule
  dataset_name: PROTEINS_50
  augmentation_method: gdss

  overfit: -1

  train_dirs:
    standard: ${oc.env:PROJECT_ROOT}/data/standard_train
    connectivity_augmented: #${oc.env:PROJECT_ROOT}/data/connectivity_augmented
  val_dir: ${oc.env:PROJECT_ROOT}/data/standard_val
  test_dir: ${oc.env:PROJECT_ROOT}/data/standard_test

  max_graphs_per_dataset:
    standard: -1
    connectivity_augmented: 512

  datasets:
    train:
      _target_: discrete_diffusion.data.graph_dataset.GraphDataset
    val:
      _target_: discrete_diffusion.data.graph_dataset.GraphDataset
    test:
      _target_: discrete_diffusion.data.graph_dataset.GraphDataset


  gpus: ${train.trainer.gpus}

  num_workers:
    train: 16
    val: 16
    test: 16

  batch_size:
    train: 16
    val: 16
    test: 1

  val_percentage: 0.1


module:
  _target_: discrete_diffusion.pl_modules.classifier_pl_module.ClassifierPLModule

  model:
    _target_: discrete_diffusion.modules.classifier.classifier.Classifier
    hidden_channels: 128
    num_classes: 2

  optimizer:
    _target_: torch.optim.Adam
    lr: 0.0001

  lr_scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
    T_0: 10
    T_mult: 2
    eta_min: 0 # min value for the lr
    last_epoch: -1
    verbose: False
