defaults:
  - data: synthetic
  - gnn_embedder: GINConv
  - _self_

module:
  _target_: discrete_diffusion.pl_modules.vgae_pl_module.VGAEPLModule

  model:
    _target_: discrete_diffusion.modules.gnn.node_embedder.NodeEmbedder
    feature_dim: ???
    num_layers_pre_post_mlp: 2
    hidden_dim_shared: 128
    embedding_dim: 128
    use_batch_norm_pre_post_mlp: true
    num_convs: 2
    dropout_rate: 0.1
    do_preprocess: true
    jump_mode: cat
    gnn: ${nn.gnn_embedder}

  optimizer:
    _target_: torch.optim.Adam
    lr: 1e-4

  lr_scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
    T_0: 10
    T_mult: 2
    eta_min: 0 # min value for the lr
    last_epoch: -1
    verbose: False
